#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
cd /home/ubuntu/grid/
export EC2_INSTANCE_ID="`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id || die \"wget instance-id has failed: $?\"`"
# Pull down the user data, which will be a zip file containing necessary information
export NODE_TEMPLATE="/home/ubuntu/grid/nodeConfigTemplate.json"
curl http://169.254.169.254/latest/user-data -o /home/ubuntu/grid/data.zip

# Now, unzip the data downloaded from the userdata
unzip -o /home/ubuntu/grid/data.zip -d /home/ubuntu/grid/
# Replace the instance ID in the node config file
sed "s/<INSTANCE_ID>/$EC2_INSTANCE_ID/g" $NODE_TEMPLATE > /home/ubuntu/grid/nodeConfig.json
# Finally, run the java process in a window so browsers can run
xvfb-run --auto-servernum --server-args='-screen 0, 1600x1200x24' java -jar /home/ubuntu/grid/selenium-server-node.jar -role node -nodeConfig /home/ubuntu/grid/nodeConfig.json -Dwebdriver.chrome.driver="/home/ubuntu/grid/chromedriver" -log /home/ubuntu/grid/grid.log &

xvfb-run --auto-servernum --server-args='-screen 0, 1600x1200x24' java -jar /home/ubuntu/grid/selenium-server-standalone-3.11.0.jar -role node -nodeConfig /home/ubuntu/grid/nodeConfig.json -Dwebdriver.chrome.driver="/home/ubuntu/grid/chromedriver" -log /home/ubuntu/grid/grid.log &
