#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
echo "Running Grid Start Node"
cd /home/ec2-user/grid-node/
export EC2_INSTANCE_ID="`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id || die \"wget instance-id has failed: $?\"`"
# Pull down the user data, which will be a zip file containing necessary information
#export NODE_TEMPLATE="/home/ubuntu/grid/nodeConfigTemplate.json"
curl http://169.254.169.254/latest/user-data -o /home/ec2-user/grid-node/data.zip

# Now, unzip the data downloaded from the userdata
unzip -o /home/ec2-user/grid-node/data.zip -d /home/ec2-user/grid-node/
# Replace the instance ID in the node config file
# sed "s/<INSTANCE_ID>/$EC2_INSTANCE_ID/g" $NODE_TEMPLATE > /home/ubuntu/grid/nodeConfig.json
# Finally, run the java process in a window so browsers can run
#xvfb-run --auto-servernum --server-args='-screen 0, 1600x1200x24' java -jar /home/ubuntu/grid/selenium-server-node.jar -role node -nodeConfig /home/ubuntu/grid/nodeConfig.json -Dwebdriver.chrome.driver="/home/ubuntu/grid/chromedriver" -log /home/ubuntu/grid/grid.log &

docker run -d -p 5555:5555 -e REMOTE_HOST="http://10.255.21.22:5555" -e HUB_PORT_4444_TCP_ADDR=10.255.21.225 -e HUB_PORT_4444_TCP_PORT=4444 selenium/node-chrome
